import serial
import serial.tools.list_ports
import json
from datetime import datetime
import time

timestamp = datetime.now().strftime("%m-%d-%Y %I:%M:%S%p")
ports = list(serial.tools.list_ports.comports())
currentPort = ""
collectorCounter = 0
sensorDataSession = []
sensorDataJson = {
    "sensorName": {
        "timestamp": "",
        "farthestDistance": "",
        "closestDistance": "",
        "averageDistance": ""
    }
}

# Find the port that the arduino is connected to
for p in ports:
    if "n/a" not in p:
        currentPort = p.device


ardiuno = serial.Serial(currentPort, 9600)
print(f"Connected to {currentPort}")

while ardiuno.readline() is not None:
    

    print(f'Sensor Data: {ardiuno.readline().decode("utf-8").strip()}')
    print(f'Collector Counter: {collectorCounter}')

    sensorDataSession.append(ardiuno.readline().decode("utf-8").strip())

    if collectorCounter == 4:

        sensorDataJson["sensorName"]["timestamp"] = str(timestamp)
        sensorDataJson["sensorName"]["farthestDistance"] = "farthest"
        sensorDataJson["sensorName"]["closestDistance"] = "closest"
        sensorDataJson["sensorName"]["averageDistance"] = sum(int(x) for x in sensorDataSession) / len(sensorDataSession)

        # Reset the collector counter and session data for the next round of data collection
        collectorCounter = 0
        sensorDataSession = []
        
        # Dump data to json file for later use in dataETL.py
        with open("sensorData.json", "w", encoding="utf-8") as f:
            json.dump(sensorDataJson, f, indent=4)

        print("delaying 1 minute before next read...")   
        # Delay 60 seconds before reading the next set of data to avoid overwhelming the system and to allow for new data to be generated by the sensor
        time.sleep(60)
    else:
        collectorCounter += 1




# add to dataframe
# clean up data
# send to azure cloud database sql
# output data using streamlit