import serial
import serial.tools.list_ports
import json
from datetime import datetime
import time
import pandas as pd
from dotenv import load_dotenv
import os
import pymssql


# Load environment variables
load_dotenv()
port = 1433 # Default port for SQL Server


# Retrieve .env values
try:
    server = os.environ['DATABASE_SERVER']
    database = os.environ['DATABASE_NAME']
    username = os.environ['DATABASE_USER']
    password = os.environ['DATABASE_PASSWORD']
except Exception as e:
    print(f"Error loading environment variables: {e}")
    exit(1)


# Find current port and initialize
ports = list(serial.tools.list_ports.comports())
currentPort = ""


# Find the port that the arduino is connected to
for p in ports:
    if "n/a" not in p:
        currentPort = p.device


arduino = serial.Serial(currentPort, 9600)
print(f"Connected to {currentPort}")


# Initialize fields
collectorCounter = 0
sensorDataSession = []
sensorDataJson = {
    "sensor_data": {

    }
}


# function for inserting the data into the azure sql database
def insertData():

    # Initialize data for the query
    dataToLoad = [
        sensorDataJson["sensor_data"]['timestamp'], # Access key value pair from the dictionary where the sensor data is stored
        sensorDataJson["sensor_data"]['device_port'],
        sensorDataJson["sensor_data"]['farthest_distance'], 
        sensorDataJson["sensor_data"]['closest_distance'], 
        sensorDataJson["sensor_data"]['average_distance']
    ]

    try:

        # Connect to the database using pymssql
        conn = pymssql.connect(
            server=server,
            user=username,
            password=password,
            database=database,
            port=port
        )

        # Initialize cursor object
        cursor = conn.cursor()

        # Set sql query
        query = "INSERT INTO sensor_data (timestamp, device_port, farthest_distance, closest_distance, average_distance) VALUES (%s, %s, %s, %s, %s)"
        
        # Execute sql query with the data values
        cursor.execute(query, dataToLoad)
        conn.commit()   # Commit the transaction
        print("Data inserted to the database Successfully!") # print success message (this will be printed if cursor.execute didnt throw any sql errors)

        cursor.close()  # Close the cursor
        conn.close()    # Close the connection

    except pymssql.Error as e:
        print(f"An error occurred: {e}")
        exit(1)



# Continously loop while sensor data is available
while arduino.readline() is not None:


    print(f'Sensor Data: {arduino.readline().decode("utf-8").strip()}')
    print(f'Collector Counter: {collectorCounter}')


    # store 5 data readings to get the average value 
    sensorDataSession.append(int(arduino.readline().decode("utf-8").strip()))


    # if total counts of data collected is 5
    if collectorCounter == 4:

        # current date time
        timestamp = datetime.now().strftime("%m-%d-%Y %I:%M:%S%p")

        # using the current session data, we perform calculations to get avg, max, min and store in the dictionary
        sensorDataJson["sensor_data"] = {
            "timestamp": timestamp,
            "device_port": currentPort,
            "farthest_distance": max(sensorDataSession),
            "closest_distance": min(sensorDataSession),
            "average_distance": sum(int(x) for x in sensorDataSession) / len(sensorDataSession)
        }
        
        # Call insertData function
        insertData()

        print("delaying 60 seconds before next read...")   
        # Delay 60 seconds before reading the next set of data to avoid overwhelming the system and to allow for new data to be generated by the sensor
        time.sleep(60)

        # Reset the collector counter and session data for the next round of data collection
        collectorCounter = 0
        sensorDataSession = []

    else:
        collectorCounter += 1